name: codingblackfemales
recipe: wordpress
config:
  database: mariadb
  php: '8.1'
  via: apache
  webroot: web
  xdebug: true
  config:
    php: .lando/config/php/php.ini
# Multisite networks must have each site listed below to work under lando
# and the URLs must match those in the wp_blogs table
proxy:
  appserver:
    - codingblackfemales.lndo.site
    - academy.codingblackfemales.lndo.site
    - jobs.codingblackfemales.lndo.site
services:
  appserver:
    composer_version: 2-latest
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
    run:
      - composer install
      - npm install
    run_as_root:
      - .lando/scripts/xdebug.sh develop,debug
    overrides:
      environment:
        XDEBUG_MODE:
        PHP_IDE_CONFIG: "serverName=appserver"
  database:
    portforward: 3307
# https://github.com/lando/lando/issues/1668#issuecomment-557090549
# events:
#   pre-wp:
#     - appserver: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
#   post-wp:
#     - appserver: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
tooling:
  node:
    service: appserver
  npm:
    service: appserver
  # https://github.com/lando/lando/issues/1668#issuecomment-772829423
  xdebug:
    description: Loads XDebug in the selected mode.
    cmd:
      - appserver: /app/.lando/scripts/xdebug.sh
    user: root
