<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'StellarWP\\Learndash\\lucatume\\DI52\\' => array($vendorDir . '/lucatume/di52/src'),
    'StellarWP\\Learndash\\WpOrg\\Requests\\' => array($vendorDir . '/rmccue/requests/src'),
    'StellarWP\\Learndash\\TrustedLogin\\' => array($vendorDir . '/trustedlogin/client/src'),
    'StellarWP\\Learndash\\Stripe\\' => array($vendorDir . '/stripe/stripe-php/lib'),
    'StellarWP\\Learndash\\StellarWP\\Validation\\' => array($vendorDir . '/stellarwp/validation/src'),
    'StellarWP\\Learndash\\StellarWP\\Telemetry\\Views_Dir\\' => array($vendorDir . '/stellarwp/telemetry/src/views'),
    'StellarWP\\Learndash\\StellarWP\\Telemetry\\Assets_Dir\\' => array($vendorDir . '/stellarwp/telemetry/src/resources'),
    'StellarWP\\Learndash\\StellarWP\\Telemetry\\' => array($vendorDir . '/stellarwp/telemetry/src/Telemetry'),
    'StellarWP\\Learndash\\StellarWP\\SuperGlobals\\' => array($vendorDir . '/stellarwp/superglobals/src/SuperGlobals'),
    'StellarWP\\Learndash\\StellarWP\\Models\\' => array($vendorDir . '/stellarwp/models/src/Models'),
    'StellarWP\\Learndash\\StellarWP\\FieldConditions\\' => array($vendorDir . '/stellarwp/field-conditions/src'),
    'StellarWP\\Learndash\\StellarWP\\DB\\' => array($vendorDir . '/stellarwp/db/src/DB'),
    'StellarWP\\Learndash\\StellarWP\\ContainerContract\\' => array($vendorDir . '/stellarwp/container-contract/src'),
    'StellarWP\\Learndash\\StellarWP\\Assets\\' => array($vendorDir . '/stellarwp/assets/src/Assets'),
    'StellarWP\\Learndash\\StellarWP\\Arrays\\' => array($vendorDir . '/stellarwp/arrays/src/Arrays'),
    'StellarWP\\Learndash\\StellarWP\\AdminNotices\\' => array($vendorDir . '/stellarwp/admin-notices/src'),
    'StellarWP\\Learndash\\SSNepenthe\\ColorUtils\\' => array($vendorDir . '/ssnepenthe/color-utils/src'),
    'StellarWP\\Learndash\\Razorpay\\Tests\\' => array($vendorDir . '/razorpay/razorpay/tests'),
    'StellarWP\\Learndash\\Razorpay\\Api\\' => array($vendorDir . '/razorpay/razorpay/src'),
    'StellarWP\\Learndash\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'StellarWP\\Learndash\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'StellarWP\\Learndash\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'StellarWP\\Learndash\\Nyholm\\Psr7\\' => array($vendorDir . '/nyholm/psr7/src'),
    'StellarWP\\Learndash\\Nexcess\\PluginAbsorber\\' => array($vendorDir . '/stellarwp/plugin-absorber/src'),
    'StellarWP\\Learndash\\MyCLabs\\Enum\\' => array($vendorDir . '/myclabs/php-enum/src'),
    'StellarWP\\Learndash\\LiquidWeb\\LicensingApiClient\\' => array($vendorDir . '/stellarwp/licensing-api-client/src'),
    'StellarWP\\Learndash\\LiquidWeb\\LicensingApiClientWordPress\\' => array($vendorDir . '/stellarwp/licensing-api-client-wordpress/src'),
    'StellarWP\\Learndash\\LiquidWeb\\Harbor\\Views\\' => array($vendorDir . '/stellarwp/harbor/src/views'),
    'StellarWP\\Learndash\\LiquidWeb\\Harbor\\Build_Dir\\' => array($vendorDir . '/stellarwp/harbor/build'),
    'StellarWP\\Learndash\\LiquidWeb\\Harbor\\Build_Dev_Dir\\' => array($vendorDir . '/stellarwp/harbor/build-dev'),
    'StellarWP\\Learndash\\LiquidWeb\\Harbor\\' => array($vendorDir . '/stellarwp/harbor/src/Harbor'),
);
