<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'cc55976d4533c9f1adaa0d60d19574f3' => $vendorDir . '/rmccue/requests/library/Deprecated.php',
    '856f6e612155f47e3a03b04082ff2907' => $vendorDir . '/razorpay/razorpay/Deprecated.php',
    '7392c808059559c71f8c76fc29a2b894' => $vendorDir . '/ssnepenthe/color-utils/inc/colors.php',
    '764b3aa198ea7dbfec7ffec3596f4b99' => $vendorDir . '/ssnepenthe/color-utils/inc/helpers.php',
    'b25e07c7e7a101e312b1be7d48882b9b' => $vendorDir . '/ssnepenthe/color-utils/inc/transformations.php',
);
