<?php
/**
 * Unit-suite actor.
 *
 * Generated by `composer test:build`, which regenerates the action trait under
 * Support/_generated whenever the suite's modules change. Custom helpers belong
 * in Support/Helper, not here.
 *
 * @package CodingBlackFemales/SlidesImporter
 */

declare(strict_types=1);

namespace CodingBlackFemales\SlidesImporter\Tests\Support;

/**
 * Inherited Methods
 * @method void wantTo($text)
 * @method void wantToTest($text)
 * @method void execute($callable)
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
 * @method void lookForwardTo($achieveValue)
 * @method void comment($description)
 * @method void pause($vars = [])
 *
 * @SuppressWarnings(PHPMD)
*/
class UnitTester extends \Codeception\Actor {

	use _generated\UnitTesterActions;

	/**
	 * Define custom actions here
	 */
}
