<?php

// autoload_static.php @generated by Composer

namespace LearnDash\Zapier\Composer\Autoload;

class ComposerStaticInit60a78823be8143459721baab7d0475e2
{
    public static $prefixLengthsPsr4 = array (
        'L' =>
        array (
            'LearnDash\\Zapier\\StellarWP\\Templates\\' => 37,
            'LearnDash\\Zapier\\StellarWP\\Arrays\\' => 34,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LearnDash\\Zapier\\StellarWP\\Templates\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/templates/src/Templates',
        ),
        'LearnDash\\Zapier\\StellarWP\\Arrays\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/arrays/src/Arrays',
        ),
    );

    public static $classMap = array (
        'LearnDash\\Zapier\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'LearnDash\\Zapier\\StellarWP\\Arrays\\Arr' => __DIR__ . '/..' . '/stellarwp/arrays/src/Arrays/Arr.php',
        'LearnDash\\Zapier\\StellarWP\\Templates\\Config' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Config.php',
        'LearnDash\\Zapier\\StellarWP\\Templates\\Part_Cache' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Part_Cache.php',
        'LearnDash\\Zapier\\StellarWP\\Templates\\Template' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Template.php',
        'LearnDash\\Zapier\\StellarWP\\Templates\\Templates' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Templates.php',
        'LearnDash\\Zapier\\StellarWP\\Templates\\Utils\\Conditions' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Utils/Conditions.php',
        'LearnDash\\Zapier\\StellarWP\\Templates\\Utils\\Paths' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Utils/Paths.php',
        'LearnDash\\Zapier\\StellarWP\\Templates\\Utils\\Strings' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Utils/Strings.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit60a78823be8143459721baab7d0475e2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit60a78823be8143459721baab7d0475e2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit60a78823be8143459721baab7d0475e2::$classMap;

        }, null, ClassLoader::class);
    }
}
