<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit60a78823be8143459721baab7d0475e2
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('LearnDash\Zapier\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \LearnDash\Zapier\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit60a78823be8143459721baab7d0475e2', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \LearnDash\Zapier\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit60a78823be8143459721baab7d0475e2', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\LearnDash\Zapier\Composer\Autoload\ComposerStaticInit60a78823be8143459721baab7d0475e2::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
